version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_migration
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: migration123
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: migration_user
      MYSQL_PASSWORD: migration_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_migration_data:/var/lib/mysql
      - ./config/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      - migration_network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb3 --collation-server=utf8mb3_turkish_ci

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: crm_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: mydatabase
      DB_USER: migration_user
      DB_PASSWORD: migration_pass
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - migration_network
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: crm_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - migration_network
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next

volumes:
  mysql_migration_data:
    driver: local

networks:
  migration_network:
    driver: bridge