-- 202507250302_10776 dosyasından çıkarılan CREATE TABLE ve INSERT INTO bölümleri
-- Tarih: 2025-01-15

-- =====================================================
-- CONTACT TABLOSU - CREATE TABLE + INSERT INTO
-- =====================================================

/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8mb4 */;
CREATE TABLE `CONTACT` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `CONTROLNAME` varchar(10) GENERATED ALWAYS AS (replace(replace(replace(replace(replace(replace(lcase(substr(replace(`NAME`,' ',''),1,10)),'ü','u'),'ğ','g'),'ı','i'),'ş','s'),'ç','c'),'ö','o')) STORED,
  `TYPE` set('P','O') CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `TITLE` varchar(4) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `JOBTITLE` varchar(500) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `ADDRESS` varchar(500) DEFAULT NULL,
  `CITY` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `STATE` char(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `COUNTRY` char(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `ZIP` varchar(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `PARENTCONTACTID` int(10) DEFAULT NULL,
  `PARENTCONTACTNAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL DEFAULT '',
  `NOTE` text CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `ORGANIZATIONTYPEID` int(10) NOT NULL DEFAULT 0,
  `ORID` int(10) NOT NULL,
  `USERID` int(10) NOT NULL,
  `DATETIME` datetime NOT NULL,
  `DATETIMEEDIT` datetime NOT NULL,
  `USERIDEDIT` int(10) NOT NULL,
  `GOOGLEID` varchar(500) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `POSITION` varchar(200) NOT NULL,
  `COORDINATE` varchar(100) NOT NULL,
  `STAMP` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ORID`,`ID`),
  KEY `DATETIME` (`DATETIME`),
  KEY `NAME` (`NAME`),
  KEY `OTYPEID` (`ORGANIZATIONTYPEID`),
  KEY `PCONTACTID` (`PARENTCONTACTID`),
  KEY `USERIDEDIT` (`USERIDEDIT`),
  KEY `CONTROLNAME` (`CONTROLNAME`),
  KEY `DATETIMEEDIT` (`DATETIMEEDIT`),
  KEY `STAMP` (`STAMP`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
 PARTITION BY HASH (`ORID`)
PARTITIONS 24;
/*!40101 SET character_set_client = @saved_cs_client */;

-- CONTACT tablosu için INSERT INTO ifadeleri (çok uzun olduğu için kısaltılmıştır)
INSERT INTO `CONTACT` VALUES 
(1,'Ferhat ÖZDABAKOĞLU','ferhatozda','P','Mr','Elektrik Mühendisi','',NULL,NULL,'','',2,'ACIBADEM PROJE YÖNETİMİ','',1,10776,29608,'2018-11-22 10:10:28','2018-11-22 12:48:04',29606,NULL,'','','2021-12-25 15:49:54'),
(2,'ACIBADEM PROJE YÖNETİMİ','acibadempr','O',NULL,NULL,'Büyükdere Cad. No:40','İstanbul','Sarıyer','','34457',0,'','01.01.2022 İTİBAREN TÜM FATURALAR ACIBADEM SAĞLIK KESİLECEK \r\nFATURALAR ; earsivfatura@apy.com\r\nearsiv@acibadem.com.tr\r\nMAİL ATILACAK- 1.9.2021\r\nULAŞIM VE NAKLİYE KDV HARİÇ 1.000 TL ÜZERİ OLURSA 2/10 TEVKİFAT UYGULANIYOR- 01.04.2021 İTİBAREN.',7,10776,29608,'2018-11-22 10:10:38','2022-01-20 17:29:21',29701,NULL,'','28.99439 41.06544','2022-01-20 14:29:21');
-- ... (diğer CONTACT kayıtları)

-- =====================================================
-- JOBSTATUSTYPE TABLOSU - CREATE TABLE + INSERT INTO
-- =====================================================

CREATE TABLE `JOBSTATUSTYPE` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `ORID` int(10) NOT NULL,
  `STAMP` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ORID`,`ID`),
  KEY `STAMP` (`STAMP`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

INSERT INTO `JOBSTATUSTYPE` VALUES 
(1,'Sipariş teslim edildi',10776,'2021-12-25 15:55:16'),
(2,'Kısmi ödeme yapıldı',10776,'2021-12-25 15:55:16'),
(3,'İmalata başlandı',10776,'2021-12-25 15:55:16'),
(5,'Sipariş alındı',10776,'2021-12-25 15:55:16'),
(6,'Uygulama Tamamlandı',10776,'2021-12-25 15:55:16'),
(7,'Peşinat Bekleniyor',10776,'2021-12-25 15:55:16');

-- =====================================================
-- USER TABLOSU - CREATE TABLE + INSERT INTO
-- =====================================================

CREATE TABLE `USER` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `EMAIL` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `KEYP` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `KEYP2` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `PERMISSION` text CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `PERMISSION2` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `COMPANY` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `ORID` int(10) NOT NULL,
  `ACTIVE` int(1) DEFAULT NULL,
  `TIMEZONE` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `COUNTRY` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `LANG` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `DATETIME` datetime DEFAULT NULL,
  `LASTLOGIN` datetime DEFAULT NULL,
  `GOOGLECRED` text CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `GOOGLEREFRESH` varchar(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `GOOGLECALENDAR` int(1) DEFAULT NULL,
  `GOOGLETASK` int(1) DEFAULT NULL,
  `CALLPBXNO` int(10) DEFAULT NULL,
  `CALLINTNO` int(10) DEFAULT NULL,
  `CALLPBXNAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXPASS` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORD` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATH` varchar(500) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTP` varchar(500) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPUSER` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPPASS` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPPORT` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPSSL` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPPASSIVE` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPDIR` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIME` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
STAMP` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ORID`,`ID`),
  KEY `DATETIME` (`DATETIME`),
  KEY `EMAIL` (`EMAIL`),
  KEY `LASTLOGIN` (`LASTLOGIN`),
  KEY `STAMP` (`STAMP`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

INSERT INTO `USER` VALUES 
(29606,'Ferhat ÖZDABAKOĞLU','ferhat@apy.com','123456',NULL,'1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100','1','ACIBADEM PROJE YÖNETİMİ',10776,1,'Europe/Istanbul','TR','tr','2018-11-22 10:10:28','2022-01-20 17:29:21','2022-01-20 14:29:21');

-- =====================================================
-- USEREMAIL TABLOSU - CREATE TABLE + INSERT INTO
-- =====================================================

CREATE TABLE `USEREMAIL` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `USERID` int(10) NOT NULL,
  `EMAIL` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `ORID` int(10) NOT NULL,
  `STAMP` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ORID`,`ID`),
  KEY `USERID` (`USERID`),
  KEY `EMAIL` (`EMAIL`),
  KEY `STAMP` (`STAMP`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

INSERT INTO `USEREMAIL` VALUES 
(1,29606,'ferhat@apy.com',10776,'2021-12-25 15:55:16');

-- =====================================================
-- SADECE CREATE TABLE OLAN TABLOLAR (INSERT YOK)
-- =====================================================

-- LEAD TABLOSU - SADECE CREATE TABLE
CREATE TABLE `LEAD` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `CONTACTID` int(10) NOT NULL,
  `CONTACTNAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL DEFAULT '',
  `LEADSTATUSID` int(10) NOT NULL,
  `LEADSTATUSNAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL DEFAULT '',
  `LEADSOURCEID` int(10) NOT NULL,
  `LEADSOURCENAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL DEFAULT '',
  `LEADTYPEID` int(10) NOT NULL,
  `LEADTYPENAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL DEFAULT '',
  `LEADCAMPAIGNID` int(10) NOT NULL,
  `LEADCAMPAIGNNAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL DEFAULT '',
  `LEADPRODUCTID` int(10) NOT NULL,
  `LEADPRODUCTNAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL DEFAULT '',
  `ORID` int(10) NOT NULL,
  `USERID` int(10) NOT NULL,
  `DATETIME` datetime NOT NULL,
  `DATETIMEEDIT` datetime NOT NULL,
  `USERIDEDIT` int(10) NOT NULL,
  `STAMP` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ORID`,`ID`),
  KEY `CONTACTID` (`CONTACTID`),
  KEY `LEADSTATUSID` (`LEADSTATUSID`),
  KEY `DATETIME` (`DATETIME`),
  KEY `DATETIMEEDIT` (`DATETIMEEDIT`),
  KEY `STAMP` (`STAMP`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- LOGIN_HISTORY TABLOSU - SADECE CREATE TABLE
CREATE TABLE `LOGIN_HISTORY` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `USERID` int(10) NOT NULL,
  `USERNAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `IP` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `USERAGENT` text CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `DATETIME` datetime NOT NULL,
  `ORID` int(10) NOT NULL,
  `STAMP` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ORID`,`ID`),
  KEY `USERID` (`USERID`),
  KEY `DATETIME` (`DATETIME`),
  KEY `IP` (`IP`),
  KEY `STAMP` (`STAMP`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- TASK TABLOSU - SADECE CREATE TABLE
CREATE TABLE `TASK` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `CONTACTID` int(10) NOT NULL,
  `CONTACTNAME` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL DEFAULT '',
  `SUBJECT` varchar(500) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `NOTE` text CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `PRIORITY` set('Low','Normal','High') CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL DEFAULT 'Normal',
  `STATUS` set('Not Started','In Progress','Completed','Waiting on someone else','Deferred') CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL DEFAULT 'Not Started',
  `PERCENTCOMPLETE` int(3) NOT NULL DEFAULT 0,
  `DATETIME` datetime DEFAULT NULL,
  `DATETIMEDUE` datetime DEFAULT NULL,
  `ORID` int(10) NOT NULL,
  `USERID` int(10) NOT NULL,
  `DATETIMEEDIT` datetime NOT NULL,
  `USERIDEDIT` int(10) NOT NULL,
  `STAMP` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ORID`,`ID`),
  KEY `CONTACTID` (`CONTACTID`),
  KEY `DATETIME` (`DATETIME`),
  KEY `DATETIMEDUE` (`DATETIMEDUE`),
  KEY `DATETIMEEDIT` (`DATETIMEEDIT`),
  KEY `STATUS` (`STATUS`),
  KEY `PRIORITY` (`PRIORITY`),
  KEY `STAMP` (`STAMP`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
 PARTITION BY HASH (`ORID`)
PARTITIONS 24;

-- USERCODES TABLOSU - SADECE CREATE TABLE
CREATE TABLE `USERCODES` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `USERID` int(10) NOT NULL,
  `CODE` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci NOT NULL,
  `DATETIME` datetime NOT NULL,
  `ORID` int(10) NOT NULL,
  `STAMP` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ORID`,`ID`),
  KEY `USERID` (`USERID`),
  KEY `CODE` (`CODE`),
  KEY `DATETIME` (`DATETIME`),
  KEY `STAMP` (`STAMP`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

-- =====================================================
-- ÖZET BİLGİLER
-- =====================================================
-- CREATE TABLE + INSERT INTO olan tablolar: CONTACT, JOBSTATUSTYPE, USER, USEREMAIL
-- Sadece CREATE TABLE olan tablolar: LEAD, LOGIN_HISTORY, TASK, USERCODES
-- Toplam 8 tablo bulunmaktadır.
-- TASK tablosunda DATETIMEDUE alanı tanımlı ancak INSERT verisi yoktur.AYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYS` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_turkish_ci DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVE` int(1) DEFAULT NULL,
  `CALLPBXRECORDPATHFTPACTIVETIMEACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVEDAYSACTIVED